//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 03:23:11 PM EET 
//


package com.telesens.afanasiev.impl.jaxb.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="station" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute ref="{}id use="required""/>
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="arcs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="arc" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute ref="{}id use="required""/>
 *                           &lt;attribute name="nodeLeftId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="nodeRightId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="routes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="route" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="arcsLink" maxOccurs="unbounded" minOccurs="2">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="arcId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{}id use="required""/>
 *                           &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="direct" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="cost" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="firstNodeId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="simpleRoutes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pair" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute ref="{}id use="required""/>
 *                           &lt;attribute name="routeForwardId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="routeBackId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="circularRoutes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="routeLink" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="routeId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stations",
    "arcs",
    "routes",
    "simpleRoutes",
    "circularRoutes"
})
@XmlRootElement(name = "busNetwork")
public class BusNetwork {

    @XmlElement(required = true)
    protected BusNetwork.Stations stations;
    @XmlElement(required = true)
    protected BusNetwork.Arcs arcs;
    @XmlElement(required = true)
    protected BusNetwork.Routes routes;
    @XmlElement(required = true)
    protected BusNetwork.SimpleRoutes simpleRoutes;
    @XmlElement(required = true)
    protected BusNetwork.CircularRoutes circularRoutes;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;

    /**
     * Gets the value of the stations property.
     * 
     * @return
     *     possible object is
     *     {@link BusNetwork.Stations }
     *     
     */
    public BusNetwork.Stations getStations() {
        return stations;
    }

    /**
     * Sets the value of the stations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusNetwork.Stations }
     *     
     */
    public void setStations(BusNetwork.Stations value) {
        this.stations = value;
    }

    /**
     * Gets the value of the arcs property.
     * 
     * @return
     *     possible object is
     *     {@link BusNetwork.Arcs }
     *     
     */
    public BusNetwork.Arcs getArcs() {
        return arcs;
    }

    /**
     * Sets the value of the arcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusNetwork.Arcs }
     *     
     */
    public void setArcs(BusNetwork.Arcs value) {
        this.arcs = value;
    }

    /**
     * Gets the value of the routes property.
     * 
     * @return
     *     possible object is
     *     {@link BusNetwork.Routes }
     *     
     */
    public BusNetwork.Routes getRoutes() {
        return routes;
    }

    /**
     * Sets the value of the routes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusNetwork.Routes }
     *     
     */
    public void setRoutes(BusNetwork.Routes value) {
        this.routes = value;
    }

    /**
     * Gets the value of the simpleRoutes property.
     * 
     * @return
     *     possible object is
     *     {@link BusNetwork.SimpleRoutes }
     *     
     */
    public BusNetwork.SimpleRoutes getSimpleRoutes() {
        return simpleRoutes;
    }

    /**
     * Sets the value of the simpleRoutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusNetwork.SimpleRoutes }
     *     
     */
    public void setSimpleRoutes(BusNetwork.SimpleRoutes value) {
        this.simpleRoutes = value;
    }

    /**
     * Gets the value of the circularRoutes property.
     * 
     * @return
     *     possible object is
     *     {@link BusNetwork.CircularRoutes }
     *     
     */
    public BusNetwork.CircularRoutes getCircularRoutes() {
        return circularRoutes;
    }

    /**
     * Sets the value of the circularRoutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusNetwork.CircularRoutes }
     *     
     */
    public void setCircularRoutes(BusNetwork.CircularRoutes value) {
        this.circularRoutes = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="arc" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute ref="{}id use="required""/>
     *                 &lt;attribute name="nodeLeftId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="nodeRightId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "arc"
    })
    public static class Arcs {

        @XmlElement(required = true)
        protected List<BusNetwork.Arcs.Arc> arc;

        /**
         * Gets the value of the arc property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the arc property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getArc().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BusNetwork.Arcs.Arc }
         * 
         * 
         */
        public List<BusNetwork.Arcs.Arc> getArc() {
            if (arc == null) {
                arc = new ArrayList<BusNetwork.Arcs.Arc>();
            }
            return this.arc;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute ref="{}id use="required""/>
         *       &lt;attribute name="nodeLeftId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="nodeRightId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Arc {

            @XmlAttribute(name = "id", required = true)
            protected long id;
            @XmlAttribute(name = "nodeLeftId", required = true)
            protected long nodeLeftId;
            @XmlAttribute(name = "nodeRightId", required = true)
            protected long nodeRightId;
            @XmlAttribute(name = "duration", required = true)
            protected int duration;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the nodeLeftId property.
             * 
             */
            public long getNodeLeftId() {
                return nodeLeftId;
            }

            /**
             * Sets the value of the nodeLeftId property.
             * 
             */
            public void setNodeLeftId(long value) {
                this.nodeLeftId = value;
            }

            /**
             * Gets the value of the nodeRightId property.
             * 
             */
            public long getNodeRightId() {
                return nodeRightId;
            }

            /**
             * Sets the value of the nodeRightId property.
             * 
             */
            public void setNodeRightId(long value) {
                this.nodeRightId = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public int getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(int value) {
                this.duration = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="routeLink" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="routeId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "routeLink"
    })
    public static class CircularRoutes {

        @XmlElement(required = true)
        protected List<BusNetwork.CircularRoutes.RouteLink> routeLink;

        /**
         * Gets the value of the routeLink property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the routeLink property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRouteLink().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BusNetwork.CircularRoutes.RouteLink }
         * 
         * 
         */
        public List<BusNetwork.CircularRoutes.RouteLink> getRouteLink() {
            if (routeLink == null) {
                routeLink = new ArrayList<BusNetwork.CircularRoutes.RouteLink>();
            }
            return this.routeLink;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="routeId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RouteLink {

            @XmlAttribute(name = "routeId", required = true)
            protected long routeId;

            /**
             * Gets the value of the routeId property.
             * 
             */
            public long getRouteId() {
                return routeId;
            }

            /**
             * Sets the value of the routeId property.
             * 
             */
            public void setRouteId(long value) {
                this.routeId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="route" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="arcsLink" maxOccurs="unbounded" minOccurs="2">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="arcId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{}id use="required""/>
     *                 &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="direct" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="cost" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="firstNodeId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "route"
    })
    public static class Routes {

        @XmlElement(required = true)
        protected List<BusNetwork.Routes.Route> route;

        /**
         * Gets the value of the route property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the route property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRoute().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BusNetwork.Routes.Route }
         * 
         * 
         */
        public List<BusNetwork.Routes.Route> getRoute() {
            if (route == null) {
                route = new ArrayList<BusNetwork.Routes.Route>();
            }
            return this.route;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="arcsLink" maxOccurs="unbounded" minOccurs="2">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="arcId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute ref="{}id use="required""/>
         *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="direct" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="cost" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="firstNodeId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "arcsLink"
        })
        public static class Route {

            @XmlElement(required = true)
            protected List<BusNetwork.Routes.Route.ArcsLink> arcsLink;
            @XmlAttribute(name = "id", required = true)
            protected long id;
            @XmlAttribute(name = "number", required = true)
            protected String number;
            @XmlAttribute(name = "description")
            protected String description;
            @XmlAttribute(name = "direct", required = true)
            protected String direct;
            @XmlAttribute(name = "cost", required = true)
            protected double cost;
            @XmlAttribute(name = "firstNodeId", required = true)
            protected long firstNodeId;

            /**
             * Gets the value of the arcsLink property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the arcsLink property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getArcsLink().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BusNetwork.Routes.Route.ArcsLink }
             * 
             * 
             */
            public List<BusNetwork.Routes.Route.ArcsLink> getArcsLink() {
                if (arcsLink == null) {
                    arcsLink = new ArrayList<BusNetwork.Routes.Route.ArcsLink>();
                }
                return this.arcsLink;
            }

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the number property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumber(String value) {
                this.number = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the direct property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDirect() {
                return direct;
            }

            /**
             * Sets the value of the direct property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDirect(String value) {
                this.direct = value;
            }

            /**
             * Gets the value of the cost property.
             * 
             */
            public double getCost() {
                return cost;
            }

            /**
             * Sets the value of the cost property.
             * 
             */
            public void setCost(double value) {
                this.cost = value;
            }

            /**
             * Gets the value of the firstNodeId property.
             * 
             */
            public long getFirstNodeId() {
                return firstNodeId;
            }

            /**
             * Sets the value of the firstNodeId property.
             * 
             */
            public void setFirstNodeId(long value) {
                this.firstNodeId = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="arcId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ArcsLink {

                @XmlAttribute(name = "arcId", required = true)
                protected long arcId;

                /**
                 * Gets the value of the arcId property.
                 * 
                 */
                public long getArcId() {
                    return arcId;
                }

                /**
                 * Sets the value of the arcId property.
                 * 
                 */
                public void setArcId(long value) {
                    this.arcId = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pair" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute ref="{}id use="required""/>
     *                 &lt;attribute name="routeForwardId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="routeBackId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pair"
    })
    public static class SimpleRoutes {

        @XmlElement(required = true)
        protected List<BusNetwork.SimpleRoutes.Pair> pair;

        /**
         * Gets the value of the pair property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pair property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPair().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BusNetwork.SimpleRoutes.Pair }
         * 
         * 
         */
        public List<BusNetwork.SimpleRoutes.Pair> getPair() {
            if (pair == null) {
                pair = new ArrayList<BusNetwork.SimpleRoutes.Pair>();
            }
            return this.pair;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute ref="{}id use="required""/>
         *       &lt;attribute name="routeForwardId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="routeBackId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Pair {

            @XmlAttribute(name = "id", required = true)
            protected long id;
            @XmlAttribute(name = "routeForwardId", required = true)
            protected long routeForwardId;
            @XmlAttribute(name = "routeBackId", required = true)
            protected long routeBackId;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the routeForwardId property.
             * 
             */
            public long getRouteForwardId() {
                return routeForwardId;
            }

            /**
             * Sets the value of the routeForwardId property.
             * 
             */
            public void setRouteForwardId(long value) {
                this.routeForwardId = value;
            }

            /**
             * Gets the value of the routeBackId property.
             * 
             */
            public long getRouteBackId() {
                return routeBackId;
            }

            /**
             * Sets the value of the routeBackId property.
             * 
             */
            public void setRouteBackId(long value) {
                this.routeBackId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="station" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute ref="{}id use="required""/>
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "station"
    })
    public static class Stations {

        @XmlElement(required = true)
        protected List<BusNetwork.Stations.Station> station;

        /**
         * Gets the value of the station property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the station property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BusNetwork.Stations.Station }
         * 
         * 
         */
        public List<BusNetwork.Stations.Station> getStation() {
            if (station == null) {
                station = new ArrayList<BusNetwork.Stations.Station>();
            }
            return this.station;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute ref="{}id use="required""/>
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Station {

            @XmlAttribute(name = "id", required = true)
            protected long id;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }

}
