//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 03:23:11 PM EET 
//


package com.telesens.afanasiev.impl.jaxb.schemes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telesens.afanasiev.impl.jaxb.schemes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telesens.afanasiev.impl.jaxb.schemes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BusNetwork }
     * 
     */
    public BusNetwork createBusNetwork() {
        return new BusNetwork();
    }

    /**
     * Create an instance of {@link BusNetwork.CircularRoutes }
     * 
     */
    public BusNetwork.CircularRoutes createBusNetworkCircularRoutes() {
        return new BusNetwork.CircularRoutes();
    }

    /**
     * Create an instance of {@link BusNetwork.SimpleRoutes }
     * 
     */
    public BusNetwork.SimpleRoutes createBusNetworkSimpleRoutes() {
        return new BusNetwork.SimpleRoutes();
    }

    /**
     * Create an instance of {@link BusNetwork.Routes }
     * 
     */
    public BusNetwork.Routes createBusNetworkRoutes() {
        return new BusNetwork.Routes();
    }

    /**
     * Create an instance of {@link BusNetwork.Routes.Route }
     * 
     */
    public BusNetwork.Routes.Route createBusNetworkRoutesRoute() {
        return new BusNetwork.Routes.Route();
    }

    /**
     * Create an instance of {@link BusNetwork.Arcs }
     * 
     */
    public BusNetwork.Arcs createBusNetworkArcs() {
        return new BusNetwork.Arcs();
    }

    /**
     * Create an instance of {@link BusNetwork.Stations }
     * 
     */
    public BusNetwork.Stations createBusNetworkStations() {
        return new BusNetwork.Stations();
    }

    /**
     * Create an instance of {@link BusNetwork.CircularRoutes.RouteLink }
     * 
     */
    public BusNetwork.CircularRoutes.RouteLink createBusNetworkCircularRoutesRouteLink() {
        return new BusNetwork.CircularRoutes.RouteLink();
    }

    /**
     * Create an instance of {@link BusNetwork.SimpleRoutes.Pair }
     * 
     */
    public BusNetwork.SimpleRoutes.Pair createBusNetworkSimpleRoutesPair() {
        return new BusNetwork.SimpleRoutes.Pair();
    }

    /**
     * Create an instance of {@link BusNetwork.Routes.Route.ArcsLink }
     * 
     */
    public BusNetwork.Routes.Route.ArcsLink createBusNetworkRoutesRouteArcsLink() {
        return new BusNetwork.Routes.Route.ArcsLink();
    }

    /**
     * Create an instance of {@link BusNetwork.Arcs.Arc }
     * 
     */
    public BusNetwork.Arcs.Arc createBusNetworkArcsArc() {
        return new BusNetwork.Arcs.Arc();
    }

    /**
     * Create an instance of {@link BusNetwork.Stations.Station }
     * 
     */
    public BusNetwork.Stations.Station createBusNetworkStationsStation() {
        return new BusNetwork.Stations.Station();
    }

}
